# Generated by Django 3.2.2 on 2021-05-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_alter_estudianteusuario_grado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='femenino',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='masculino',
            field=models.BooleanField(default=False),
        ),
    ]
