# Generated by Django 3.2.2 on 2021-05-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_periodo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='profesor',
            field=models.BooleanField(default=False),
        ),
    ]
