# Generated by Django 3.2.2 on 2021-05-07 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_usuario_profesor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notas_periodos',
            name='materia',
        ),
        migrations.RemoveField(
            model_name='notas_periodos',
            name='nota',
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(choices=[('MATEMATICA', 'Matematica'), ('INGLES', 'Ingles'), ('SOCIALES', 'Sociales')], max_length=10)),
                ('nota', models.FloatField()),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.periodo')),
            ],
        ),
    ]
