# Generated by Django 3.2.2 on 2021-05-18 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_usuario_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='jornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('color', models.CharField(default='#99C9FF', max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='estudianteusuario',
            name='jornada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dashboard.jornada'),
        ),
    ]
