# Generated by Django 3.2.2 on 2021-05-07 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_auto_20210507_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='Dashboard.periodo'),
        ),
    ]
