# Generated by Django 3.2.2 on 2021-05-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_auto_20210518_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='auditor',
            field=models.BooleanField(default=False),
        ),
    ]
