# Generated by Django 3.2.2 on 2021-05-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_alter_materia_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='director',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='subdirector',
            field=models.BooleanField(default=False),
        ),
    ]
